### ISSUE TITLE
samtools requirement is version-specific

### ISSUE THREAD

**Issue by kwongj** [jhawkey/IS_mapper#11]
Might be worth explicitly pointing out that it fails if the wrong version of samtools is installed - I think the sort syntax changed in later versions.

It's mainly for people like me who don't read the docs carefully enough!

```
jkwong1@mdu1:~/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293$ ismap --reads $(mdu-reads -f R12 2014-17293) --queries ../Tn4401a.fa --typingRef ../KP_KPNIH24.gbk --runtype typing --output test1

...

Building a new DB, current time: 02/09/2016 17:41:58
New DB name:   /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/Tn4401a.fa
New DB title:  ../Tn4401a.fa
Sequence type: Nucleotide
Keep Linkouts: T
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 1 sequences in 0.000435114 seconds.
/home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/KP_KPNIH24.fasta.bwt
02/09/2016 17:41:59 Building bwa index for /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/KP_KPNIH24.fasta...
02/09/2016 17:41:59 Running: bwa index /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/KP_KPNIH24.fasta
[bwa_index] Pack FASTA... 0.05 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 1.10 seconds elapse.
[bwa_index] Update BWT... 0.04 sec
[bwa_index] Pack forward-only FASTA... 0.02 sec
[bwa_index] Construct SA from BWT and Occ... 0.53 sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa index /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/KP_KPNIH24.fasta
[main] Real time: 1.823 sec; CPU: 1.751 sec
02/09/2016 17:42:01 Running: bwa mem /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/KP_KPNIH24.fasta /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/2014-17293_Tn4401a_LeftFinal.fastq > /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/2014-17293_5_KP_KPNIH24_Tn4401a.sam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 177 sequences (15221 bp)...
[M::mem_process_seqs] Processed 177 reads in 0.012 CPU sec, 0.011 real sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa mem /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/KP_KPNIH24.fasta /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/2014-17293_Tn4401a_LeftFinal.fastq
[main] Real time: 0.022 sec; CPU: 0.019 sec
02/09/2016 17:42:01 Running: bwa mem /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/KP_KPNIH24.fasta /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/2014-17293_Tn4401a_RightFinal.fastq > /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/2014-17293_3_KP_KPNIH24_Tn4401a.sam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 184 sequences (15595 bp)...
[M::mem_process_seqs] Processed 184 reads in 0.012 CPU sec, 0.012 real sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa mem /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/KP_KPNIH24.fasta /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/2014-17293_Tn4401a_RightFinal.fastq
[main] Real time: 0.022 sec; CPU: 0.019 sec
02/09/2016 17:42:01 Running: samtools view -Sb /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/2014-17293_5_KP_KPNIH24_Tn4401a.sam > /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/2014-17293_5_KP_KPNIH24_Tn4401a.bam
02/09/2016 17:42:01 Running: samtools view -Sb /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/2014-17293_3_KP_KPNIH24_Tn4401a.sam > /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/2014-17293_3_KP_KPNIH24_Tn4401a.bam
02/09/2016 17:42:01 Running: samtools sort /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/2014-17293_5_KP_KPNIH24_Tn4401a.bam 2014-17293_5_KP_KPNIH24_Tn4401a.sorted
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  -@, --threads INT
             Set number of sorting and compression threads [1]
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
Traceback (most recent call last):
  File "/bio/linuxbrew/bin/ismap", line 9, in <module>
    load_entry_point('ISMapper==0.1.3', 'console_scripts', 'ismap')()
  File "/bio/linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/ismap/ismap.py", line 609, in main
    run_command(['samtools', 'sort', five_to_ref_bam, five_bam_sorted], shell=True)
  File "/bio/linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/ismap/ismap.py", line 99, in run_command
    raise CommandError({"message": message})
ismap.ismap.CommandError: {'message': "Command 'samtools sort /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293/2014-17293_Tn4401a_temp/2014-17293_5_KP_KPNIH24_Tn4401a.bam 2014-17293_5_KP_KPNIH24_Tn4401a.sorted' failed with non-zero exit status: 1"}
jkwong1@mdu1:~/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293$ ll $(which samtools)
lrwxrwxrwx. 1 tseemann domain^users 35 Feb  3 16:49 /bio/linuxbrew/bin/samtools -> ../Cellar/samtools/1.3/bin/samtools*
jkwong1@mdu1:~/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293$ 
```

**Comment by jhawkey** [comment]
Thanks for reporting this Jason! I will add it to my next update. Up to version 0.1.19 should work, but after that I (clearly!) haven't done any testing.

**Comment by katholt** [comment]
Hi Jane,
Have a look at the check_versions functions in srst2.py, we have had to deal with this also.
Kat

-----------
A/Prof Kathryn Holt
NHMRC Career Development Fellow
Centre for Systems Genomics
and Dept Biochemistry & Molecular Biology
University of Melbourne
kholt@unimelb.edu.au<mailto:kholt@unimelb.edu.au> • @DrKatHolt
http://holtlab.net • http://SysGenMelb.org
+61 3 9035 3155


On 10 February 2016 at 11:26:35 am, Jane Hawkey (notifications@github.com<mailto:notifications@github.com>) wrote:

Thanks for reporting this Jason! I will add it to my next update. Up to version 0.1.19 should work, but after that I (clearly!) haven't done any testing.

**Comment by pryratess** [comment]
Hi!
I have the same problem with Samtools version 1.3.1. Is there any way to make it work?

**Comment by jhawkey** [comment]
Anders' pull request has now been incorporated into the latest update (v0.1.5)
