### ISSUE TITLE
ISmapper doesn't seem to like multi-sequence references?

### ISSUE THREAD

**Issue by kwongj** [jhawkey/IS_mapper#14]
Hi Jane,

Tried to run IS mapper today:

```
$ ismap --reads $(mdu-reads -f R12 2014-17293) --queries Tn4401a.fa --typingRef KP_KPNIH24.gbk --runtype typing --output 2012-17293

04/19/2016 08:27:03 Running: create_typing_out.py --intersect /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_KP_KPNIH24_Tn4401a_intersect.bed --closest /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_KP_KPNIH24_Tn4401a_closest.bed --left_bed /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_5_KP_KPNIH24_Tn4401a_merged.sorted.bed --right_bed /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_3_KP_KPNIH24_Tn4401a_merged.sorted.bed --left_unpaired /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_KP_KPNIH24_Tn4401a_left_unpaired.bed --right_unpaired /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_KP_KPNIH24_Tn4401a_right_unpaired.bed --seq Tn4401a.fa --ref KP_KPNIH24.gbk --temp /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_Tn4401a_temp/ --cds locus_tag gene product --trna locus_tag product --rrna locus_tag product --min_range 0.2 --max_range 1.1 --output /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_Tn4401a --igv 0 --chr_name not_specified
Traceback (most recent call last):
  File "/bio/linuxbrew/bin/create_typing_out.py", line 543, in <module>
    main()
  File "/bio/linuxbrew/bin/create_typing_out.py", line 254, in main
    genbank = SeqIO.read(args.ref, 'genbank')
  File "/bio/linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 665, in read
    raise ValueError("More than one record found in handle")
ValueError: More than one record found in handle
Traceback (most recent call last):
  File "/bio/linuxbrew/bin/ismap", line 9, in <module>
    load_entry_point('ISMapper==0.1.4', 'console_scripts', 'ismap')()
  File "/bio/linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/ismap/ismap.py", line 648, in main
    '--max_range', args.max_range, '--output', current_dir + sample + '_' + query_name, '--igv', igv_flag, '--chr_name', args.chr_name], shell=True)
  File "/bio/linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/ismap/ismap.py", line 101, in run_command
    raise CommandError({"message": message})
ismap.ismap.CommandError: {'message': "Command 'create_typing_out.py --intersect /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_KP_KPNIH24_Tn4401a_intersect.bed --closest /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_KP_KPNIH24_Tn4401a_closest.bed --left_bed /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_5_KP_KPNIH24_Tn4401a_merged.sorted.bed --right_bed /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_3_KP_KPNIH24_Tn4401a_merged.sorted.bed --left_unpaired /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_KP_KPNIH24_Tn4401a_left_unpaired.bed --right_unpaired /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_KP_KPNIH24_Tn4401a_right_unpaired.bed --seq Tn4401a.fa --ref KP_KPNIH24.gbk --temp /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_Tn4401a_temp/ --cds locus_tag gene product --trna locus_tag product --rrna locus_tag product --min_range 0.2 --max_range 1.1 --output /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_Tn4401a --igv 0 --chr_name not_specified' failed with non-zero exit status: 1"}
```

The reference I was using has a 5.4 Mbp chromosome plus 3 plasmids. The IS elements can be either on plasmid or chromosome.

Seemed to run ok, if I just used chromosome or plasmid as the reference. Have you found this to be a problem before? I can run them separately, just would be more convenient if together. Also annoying if my reference has multiple chromosomes or has >20 plasmids!

Sorry for "bugging" you!

Thanks,

Jason

**Comment by jhawkey** [comment]
At this stage ISMapper only accepts a single reference to type against. You're right, it is annoying to have to run it against 20 different plasmids individually.

I'm thinking about how I would output the results of the run if there were multiple entries in the genbank - would you prefer a single table with an ID column letting you know which entry the hit was in, or separate tables for each entry?

**Comment by kwongj** [comment]
I think one table with an ID column would be preferable.

Just talking with Torsten, it might be a biopython issue again, in that it might not support multi-sequence genbank files ...

**Comment by kwongj** [comment]
Thanks for replying!

**Comment by jhawkey** [comment]
BioPython does support multi genbank sequence files, but you need to change the command from SeqIO.read to SeqIO.parse. This is an easy fix, as I'm pretty sure SeqIO.parse handles single entry genbank and fasta files. 

I've noted this feature down and I think it's definitely worth adding, but it might be a while before I get to it. I'm planning an update soon to fix some other bugs, and I'll try to add this feature in, but it might have to wait until the update after that.
