### ISSUE TITLE
is there any way to allow IS mapper to accept Locus Identifiers of any length?

### ISSUE THREAD

**Issue by kwongj** [jhawkey/IS_mapper#15]
is there any way to allow IS mapper to accept Locus Identifiers of any length?

```
04/19/2016 14:19:12 Running: create_typing_out.py --intersect /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_pCfKPC_Tn4401a_intersect.bed --closest /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_pCfKPC_Tn4401a_closest.bed --left_bed /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_5_pCfKPC_Tn4401a_merged.sorted.bed --right_bed /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_3_pCfKPC_Tn4401a_merged.sorted.bed --left_unpaired /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_pCfKPC_Tn4401a_left_unpaired.bed --right_unpaired /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_pCfKPC_Tn4401a_right_unpaired.bed --seq Tn4401a.fa --ref pCfKPC.gbk --temp /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_Tn4401a_temp/ --cds locus_tag gene product --trna locus_tag product --rrna locus_tag product --min_range 0.2 --max_range 1.1 --output /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_Tn4401a --igv 0 --chr_name not_specified
Traceback (most recent call last):
  File "/bio/linuxbrew/bin/create_typing_out.py", line 543, in <module>
    main()
  File "/bio/linuxbrew/bin/create_typing_out.py", line 536, in main
    SeqIO.write(genbank, args.output + '_annotated.gbk', 'genbank')
  File "/bio/linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 472, in write
    count = writer_class(fp).write_file(sequences)
  File "/bio/linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/Bio/SeqIO/Interfaces.py", line 211, in write_file
    count = self.write_records(records)
  File "/bio/linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/Bio/SeqIO/Interfaces.py", line 196, in write_records
    self.write_record(record)
  File "/bio/linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/Bio/SeqIO/InsdcIO.py", line 731, in write_record
    self._write_the_first_line(record)
  File "/bio/linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/Bio/SeqIO/InsdcIO.py", line 556, in _write_the_first_line
    raise ValueError("Locus identifier %r is too long" % str(locus))
ValueError: Locus identifier 'pCfKPC_contig000001' is too long
Traceback (most recent call last):
  File "/bio/linuxbrew/bin/ismap", line 9, in <module>
    load_entry_point('ISMapper==0.1.4', 'console_scripts', 'ismap')()
  File "/bio/linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/ismap/ismap.py", line 648, in main
    '--max_range', args.max_range, '--output', current_dir + sample + '_' + query_name, '--igv', igv_flag, '--chr_name', args.chr_name], shell=True)
  File "/bio/linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/ismap/ismap.py", line 101, in run_command
    raise CommandError({"message": message})
ismap.ismap.CommandError: {'message': "Command 'create_typing_out.py --intersect /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_pCfKPC_Tn4401a_intersect.bed --closest /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_pCfKPC_Tn4401a_closest.bed --left_bed /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_5_pCfKPC_Tn4401a_merged.sorted.bed --right_bed /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_3_pCfKPC_Tn4401a_merged.sorted.bed --left_unpaired /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_pCfKPC_Tn4401a_left_unpaired.bed --right_unpaired /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_pCfKPC_Tn4401a_right_unpaired.bed --seq Tn4401a.fa --ref pCfKPC.gbk --temp /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_Tn4401a_temp/ --cds locus_tag gene product --trna locus_tag product --rrna locus_tag product --min_range 0.2 --max_range 1.1 --output /home/jkwong1/Kpneumo/KPC/new.ASA/plasmid/ismapper/2014-17293_Tn4401a --igv 0 --chr_name not_specified' failed with non-zero exit status: 1"}
```

**Comment by jhawkey** [comment]
Unfortunately this is BioPython complaining, not ISMapper. It's very frustrating! I keep my locus identifiers less than 10 characters to avoid issues with BioPython.
