### ISSUE TITLE
No paired reads found

### ISSUE THREAD

**Issue by YiweiZhu** [jhawkey/IS_mapper#39]
Hi, when I run the test, ismap exits with the error:
Traceback (most recent call last):
  File "/data3/zyw/miniconda3/envs/python36/bin/ismap", line 10, in <module>
    sys.exit(main())
  File "/data3/zyw/miniconda3/envs/python36/bin/ismap.py", line 195, in main
    raise NoSeqError('No paired read sets found, ISMapper exiting')
ismap.NoSeqError: No paired read sets found, ISMapper exiting

What's the matter?

**Comment by YiweiZhu** [comment]
I change "fq.gz" to "fastq.gz", then the problem is solved.
