### ISSUE TITLE
Insertion site detected between first ([0]) and second ([1]) feature causes last feature ([-1]) to be selected

### ISSUE THREAD

**Issue by rpetit3** [jhawkey/IS_mapper#42]
Hi Jane!

I recently received a "THIS SHOULDN'T HAPPEN" error with ISMapper. I was wondering if you could recall why it shouldn't, or had any advice on how to avoid it. Based on the STDOUT (see below) it looks like the left and right counts aren't the same.

Figured I check with you before I dug into it.

Thank you!
Robert

```
Caused by:
  Process `insertion_sequences (GA52847 - IS150)` terminated with an error exit status (1)

Command executed [/home/rpetit3/miniconda3/envs/bactopia-1.3.0/share/bactopia-1.3.0/templates/insertion_sequences.sh]:

  #!/bin/bash
  set -e
  set -u

  if [ "false" == "true" ]; then
      mkdir -p insertion-sequences
      touch insertion-sequences/GA52847-IS150.log
  else
        if [[ false == "true" ]]; then
            gunzip -f GA52847.gbk
        fi

        ismap --reads GA52847_R*.fastq.gz \
              --queries IS150.fasta \
              --reference GA52847.gbk \
              --log GA52847-IS150 \
              --min_clip 10 \
              --max_clip 30 \
              --cutoff 6 \
              --novel_gap_size 15 \
              --min_range 0.9 \
              --max_range 1.1 \
              --merging 100 \
              --T 30 \
              --t 2

        mv GA52847 insertion-sequences
        mv GA52847-IS150.log insertion-sequences
  fi

Command exit status:
  1

Command output:
  left index
  2 - THIS SHOULDN'T HAPPEN!
  right index
  4

Command error:
  [bwa_index] 0.05 seconds elapse.
  [bwa_index] Update BWT... 0.00 sec
  [bwa_index] Pack forward-only FASTA... 0.00 sec
  [bwa_index] Construct SA from BWT and Occ... 0.04 sec
  [main] Version: 0.7.17-r1188
  [main] CMD: bwa index /tmp/nxf.9LxVZhbJcx/GA52847/IS150/tmp/GA52847_2.fasta
  [main] Real time: 0.100 sec; CPU: 0.094 sec
  [M::bwa_idx_load_from_disk] read 0 ALT contigs
  [M::process] read 555 sequences (50113 bp)...
  [M::mem_process_seqs] Processed 555 reads in 0.036 CPU sec, 0.018 real sec
  [main] Version: 0.7.17-r1188
  [main] CMD: bwa mem -t 2 /tmp/nxf.9LxVZhbJcx/GA52847/IS150/tmp/GA52847_2.fasta /tmp/nxf.9LxVZhbJcx/GA52847/IS150/GA52847_IS150_left_final.fastq
  [main] Real time: 0.021 sec; CPU: 0.039 sec
  [M::bwa_idx_load_from_disk] read 0 ALT contigs
  [M::process] read 512 sequences (46597 bp)...
  [M::mem_process_seqs] Processed 512 reads in 0.036 CPU sec, 0.018 real sec
  [main] Version: 0.7.17-r1188
  [main] CMD: bwa mem -t 2 /tmp/nxf.9LxVZhbJcx/GA52847/IS150/tmp/GA52847_2.fasta /tmp/nxf.9LxVZhbJcx/GA52847/IS150/GA52847_IS150_right_final.fastq
  [main] Real time: 0.021 sec; CPU: 0.039 sec
  [bwa_index] Pack FASTA... 0.00 sec
  [bwa_index] Construct BWT for the packed sequence...
  [bwa_index] 0.04 seconds elapse.
  [bwa_index] Update BWT... 0.00 sec
  [bwa_index] Pack forward-only FASTA... 0.00 sec
  [bwa_index] Construct SA from BWT and Occ... 0.02 sec
  [main] Version: 0.7.17-r1188
  [main] CMD: bwa index /tmp/nxf.9LxVZhbJcx/GA52847/IS150/tmp/GA52847_3.fasta
  [main] Real time: 0.072 sec; CPU: 0.066 sec
  [M::bwa_idx_load_from_disk] read 0 ALT contigs
  [M::process] read 555 sequences (50113 bp)...
  [M::mem_process_seqs] Processed 555 reads in 0.031 CPU sec, 0.016 real sec
  [main] Version: 0.7.17-r1188
  [main] CMD: bwa mem -t 2 /tmp/nxf.9LxVZhbJcx/GA52847/IS150/tmp/GA52847_3.fasta /tmp/nxf.9LxVZhbJcx/GA52847/IS150/GA52847_IS150_left_final.fastq
  [main] Real time: 0.018 sec; CPU: 0.034 sec
  [M::bwa_idx_load_from_disk] read 0 ALT contigs
  [M::process] read 512 sequences (46597 bp)...
  [M::mem_process_seqs] Processed 512 reads in 0.033 CPU sec, 0.017 real sec
  [main] Version: 0.7.17-r1188
  [main] CMD: bwa mem -t 2 /tmp/nxf.9LxVZhbJcx/GA52847/IS150/tmp/GA52847_3.fasta /tmp/nxf.9LxVZhbJcx/GA52847/IS150/GA52847_IS150_right_final.fastq
  [main] Real time: 0.020 sec; CPU: 0.036 sec
  Traceback (most recent call last):
    File "/opt/conda/envs/bactopia-insertion_sequences/bin/ismap", line 12, in <module>
      sys.exit(main())
    File "/opt/conda/envs/bactopia-insertion_sequences/bin/ismap.py", line 229, in main
      args.novel_gap_size, args.cds, args.rrna, args.trna, tmp_output_folder, sample.prefix)
    File "/opt/conda/envs/bactopia-insertion_sequences/bin/create_output.py", line 731, in create_typing_output
      new_hit.get_flanking_genes(ref_gbk_obj, ref_feature_list)
    File "/opt/conda/envs/bactopia-insertion_sequences/bin/create_output.py", line 97, in get_flanking_genes
      print('left position: ' + str(self.left_pos))
  AttributeError: 'ISHit' object has no attribute 'left_pos'

Work dir:
  /home/rpetit3/projects/nthi/bactopia/work/cb/2e370c6ae1abfee964618115a5a70c

```

**Comment by rpetit3** [comment]
I dug into it a little bit. I'm using Genbank from an assembled genome. In my case I think a insertion site is being detected between the first (0) and second (1) features of a contig. So looking at the code here: https://github.com/jhawkey/IS_mapper/blob/master/scripts/create_output.py#L194-L209

I'm going to give the values I get that are cause the `2 - THIS SHOULDN'T HAPPEN` error.
```
    def findFeatureBeforePosition(self, features, isPosition, m):
        # If we are looking for the feature to the left of the
        # IS position, then either m-1 or m is our answer

        # If the start of the m feature is after the IS position,
        # then m is after the IS and m-1 is the correct feature

        """
        My Values
        m = 0
        isPosition = 3102
        features[m][0] = 760
        features[m - 1][1] =  162812 (because it turns into features[-1][1])
        features[m][1] = 2992
        """

        # This fails because 760 > 3102 is not true
        if features[m][0] > isPosition:
            return features[m - 1][2]

        # If both m and m+1 features are before the IS position,
        # then m will be closer to the IS and is the correct feature

        # This fails because ((162812 < 3102) and (2992 < 3102)) is not true
        elif features[m - 1][1] < isPosition and features[m][1] < isPosition:
            return features[m][2]

        else:
            return "2 - THIS SHOULDN'T HAPPEN!"
```

So question I have does the following change make sense?

```
        if features[m][1] < isPosition:
            # If its the first feature, use it, do not take the last feature
            if features[m - 1][1] < isPosition or not m:
                return features[m][2]
```

With this change everything works out no problem. But I'm not sure if its still valid or me just *making it work*.

**Comment by jhawkey** [comment]
Hi Rob,

When that code was written I was hoping to never see that error message!  If I'm understanding the issue correctly, then yes, I think your fix works and is still valid. You are correct that this issue is occuring because the IS site is at the very start of the contig between the first two features (clearly an edge case that I haven't come across before!)

Just so you're aware, ISMapper in its current form wasn't designed to work with incomplete genomes as references. It was built specifically to compare your reads to a completed reference genome. The new version allows multi-entry genbanks so you can compare a chromosome and its associated plasmid(s) in the same run, but isn't really designed for instances where the contigs could connect together (as is the case for an incomplete genome).

Anyway, happy to incorporate this fix into a future update.

**Comment by rpetit3** [comment]
Thanks Jane! You caught me! Are you by chance aware of a list of good reference genomes to use for any given IS element? If not, do you have a recommendation for selecting a reference (e.g. should it contain the full IS element, or is insertion sites enough)?

I think I might start putting a list together and would definitely share it here. Haha so you won't have me misusing ISMapper again.

Thanks again! I'll submit a PR.

**Comment by rpetit3** [comment]
I was thinking something like if you're looking for to see if your Hflu samples have reads associated with IS1016 insertion sites, 'X' is a good reference to use to test that.

I've found the same, a reference without the IS element has been working better for me.

Thanks for the info!
