### ISSUE TITLE
UnboundLocalError: local variable 'm' referenced before assignment (probably another edge case)

### ISSUE THREAD

**Issue by rpetit3** [jhawkey/IS_mapper#43]
Hi Jane!

Sorry to bug you again! I think I've found another edge case, due to an unreferenced variable.

Error:
```
Traceback (most recent call last):
    File "/opt/conda/envs/bactopia-insertion_sequences/bin/ismap", line 10, in <module>
      sys.exit(main())
    File "/opt/conda/envs/bactopia-insertion_sequences/bin/ismap.py", line 229, in main
      args.novel_gap_size, args.cds, args.rrna, args.trna, tmp_output_folder, sample.prefix)
    File "/opt/conda/envs/bactopia-insertion_sequences/bin/create_output.py", line 732, in create_typing_output
      new_hit.get_flanking_genes(ref_gbk_obj, ref_feature_list)
    File "/opt/conda/envs/bactopia-insertion_sequences/bin/create_output.py", line 89, in get_flanking_genes
      left_feature_index = self.binary_search(feature_list, 'L')
    File "/opt/conda/envs/bactopia-insertion_sequences/bin/create_output.py", line 169, in binary_search
      return self.findFeatureBeforePosition(features, isPosition, m)
  UnboundLocalError: local variable 'm' referenced before assignment
```

Issue is here: https://github.com/jhawkey/IS_mapper/blob/master/scripts/create_output.py#L162-L172

Here's the code with `$` denoting the lines of interest.
```
def binary_search(self, features, direction):
    if direction == 'R':
        isPosition = self.y
    else:
        isPosition = self.x
    min = 0
    max = len(features) - 1

    while True:

        # If the min has exceeded the max, then the IS position is not
        # inside a feature, and m will now be pointing to a
        # feature next to the IS position.
        if max < min:
            if direction == 'R':
$               return self.findFeatureAfterPosition(features, isPosition, m)
            else:
$               return self.findFeatureBeforePosition(features, isPosition, m)

        # Find the midpoint and save the feature attributes
$       m = (min + max) // 2  
....
```

Is it safe to just move `m = (min + max) // 2` above the if statement?

ISMapper is great! 

Thanks Jane!
Robert

**Comment by rpetit3** [comment]
I know what happened. Because I'm using an assembled genome, there was a contig without any annotated features. This makes `max = len(features) - 1` become -1. 

Obviously this wouldn't happen if I were using a completed genome. No worries though! I'm going to stop using assembled genomes and switch to completed.

Thanks again for ISMapper!
