### ISSUE TITLE
Example code does not run 

### ISSUE THREAD

**Issue by Jewekks** [jhawkey/IS_mapper#47]
After installing the program and the requirements the example code provided does not run correctly. Output:
ismap.NoSeqError: No paired read sets found, ISMapper exiting

Any idea what is going wrong?

**Comment by Jewekks** [comment]
Prior code is

Traceback (most recent call last):
  File "/Users/opt/anaconda3/envs/ismapper-bioconda/bin/ismap", line 10, in <module>
    sys.exit(main())
  File "/Users/opt/anaconda3/envs/ismapper-bioconda/bin/ismap.py", line 195, in main
    raise NoSeqError('No paired read sets found, ISMapper exiting')
ismap.NoSeqError: No paired read sets found, ISMapper exiting

**Comment by Jewekks** [comment]
@jhawkey
